# Generated by Django 2.1.1 on 2018-10-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180930_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='occur',
            field=models.IntegerField(default=0),
        ),
    ]
