# Generated by Django 2.1.1 on 2018-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181001_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
