# Generated by Django 2.1.1 on 2018-10-10 20:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181001_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 20, 36, 59, 931797, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='list',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 20, 36, 59, 931797, tzinfo=utc)),
        ),
    ]
