# Generated by Django 2.1.1 on 2018-10-11 01:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181010_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 1, 39, 18, 28048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='list',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 1, 39, 18, 28048, tzinfo=utc)),
        ),
    ]
